config/routes.rb
Rails.application.routes.draw do
  resources :server, only: [:show]
  resources :systems, only: [:index]
  resources :software, only: [:index]
  resources :sources, only: [:index]
  resources :details, only: [:index]

  get '/summary/index'
  root 'summary#index'
end

app/controllers/summary_controller.rb
# This handles reporting methods, only taking the data that's already in the
# database and presenting it for various functions.
class SummaryController < ApplicationController
  require 'yaml'

  def index
    # Set options for viewing.
    @opt = {}
    @opt['show_only_flagged'] = 1 if params['show_only_flagged']

    # Find all data for the catagories we care about.
    categories = %w(general puppetstatus puppetfacts vmware nessus)
    records = Server.includes(:details).where(details: { category: categories })
    @servers = convert_yaml(records)

    # Flags will be marked on any host that has a field or fields that have
    # actionable data.  It will mirror the main servers hash separately.
    @flags = check_flags(@servers)
  end

  # Check all hosts for any flagged fields, returning the flags.
  def check_flags(hosts)
    flags = {}
    hosts.keys.each do |host|
      flags[host] = {}

      if hosts[host].key?('puppetstatus')
        if flag_content?(hosts[host]['puppetstatus']['too_quiet'])
          fields = %w(puppetstatus too_quiet)
          flags[host][fields] = 1
        end
        if flag_content?(hosts[host]['puppetstatus']['failed'])
          fields = %w(puppetstatus failed)
          flags[host][fields] = 1
        end
      end

      if hosts[host].key?('nessus')
        if flag_positive?(hosts[host]['nessus']['total'])
          fields = %w(nessus total)
          flags[host][fields] = 1
        end
      end

    end
    flags
  end

  # Flag for any field that should only be either nil or ''.
  def flag_content?(value)
    return false if value.nil?
    return false if value == ''
    true
  end

  # Flag for any field that should never actually have a count on it.
  def flag_positive?(count)
    return false if count.nil?
    return true if count > 0
    false
  end
end

app/helpers/summary_helper.rb
module SummaryHelper

  # Decide if a host is expired.  We do this by checking to see if the server
  # has less than some required amount of data.  Formerly upgrades would
  # cache for several weeks, which meant that a server only with upgrade data
  # would still be considered expired.  We keep this check in case we come up
  # with other cases in the future.
  def expired_host(server)
    server.keys.each do |detail|
      next if detail == 'upgrades'
      next unless server[detail].is_a?(Hash)
      return false if server[detail].keys.count > 0
    end

    true
  end
end

app/views/summary/index.html.erb
<div id="top_navigation">
  <%= render_navigation(:level => 1) %>
</div>

<p>
  <%= form_tag('/', method: 'get') do %>
    <%= label_tag(:show_only_flagged, 'View only flagged servers:') %>
    <%= check_box_tag(:show_only_flagged, 1, @opt['show_only_flagged']) %>
    <%= submit_tag('Search') %>
  <% end %>
</p>

<table id="server_list" class="display">
  <thead>
    <tr>
      <td>Host</td>
      <td>Puppet Failure</td>
      <td>Puppet Quiet</td>
      <td>Puppetboard</td>
      <td>Nagios</td>
      <td>DevOpsDocs</td>
      <td>Nessus Crit/High/Medium</td>
    </tr>
  </thead>
  <tbody>
    <% @servers.keys.sort.each do |hostname| %>
      <% next if @opt['show_only_flagged'] == 1 && @flags[hostname].empty? %>
      <% next if expired_host(@servers[hostname]) %>
      <% next if @servers[hostname]['vmware'].key?('template') && @servers[hostname]['vmware']['template'] == 't' %>
      <tr>
        <td><%= link_to(shorthost(hostname), server_path(shorthost(hostname))) %></td>
        <td class="<%= status_flag(@flags, hostname, ['puppetstatus', 'failed']) %>">
            <%= asterisk(check_child(@servers[hostname]['puppetstatus'], 'failed')) %>
        </td>
        <td class="<%= status_flag(@flags, hostname, ['puppetstatus', 'too_quiet']) %>">
            <%= check_child(@servers[hostname]['puppetstatus'], 'too_quiet') %>
        </td>
        <td>
          <% # Making the assumption that if something has no basic puppet fact, it's not in puppet. %>
          <% if child_set(@servers[hostname]['puppetfacts'], 'environment') %>
            <a href="https://sulpuppet-board.stanford.edu/node/<%= hostname %>" target="_blank">
                Puppet Details
            </a>
          <% end %>
        </td>
        <td>
          <% # Making the assumption that if something has no basic puppet fact, it's not configured for nagios. %>
          <% if child_set(@servers[hostname]['puppetfacts'], 'environment') %>
            <a href="https://sul-nagios-stage.stanford.edu/nagios/cgi-bin/status.cgi?host=<%= shorthost(hostname) %>" target="_blank">
                Nagios
            </a>
          <% end %>
        </td>
        <td>
          <% if child_set(@servers[hostname]['puppetfacts'], 'operations_concerns_url') %>
            <a href="<%= @servers[hostname]['puppetfacts']['operations_concerns_url'] %>" target="_blank">
                DevOpsDocs
            </a>
          <% end %>
        </td>
        <td class="<%= status_flag(@flags, hostname, ['nessus', 'total']) %>">
          <% if child_set(@servers[hostname]['nessus'], 'total') %>
          <a href="<%= @servers[hostname]['nessus']['url'] %>" target="_blank">
            <%= @servers[hostname]['nessus']['critical'] %> /
            <%= @servers[hostname]['nessus']['high'] %> /
            <%= @servers[hostname]['nessus']['medium'] %>
          </a>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>